name: Build

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set executable permissions for gradlew
      run: chmod +x ./gradlew

    - name: Run Gradle build
      run: ./gradlew build
