name: pipelines

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env.properties file
        run: |
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> env.properties

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build

  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Emulator System Image
        uses: actions/cache@v3
        with:
          path: ~/.android/avd/
          key: ${{ runner.os }}-emulator-${{ hashFiles('**/build.gradle', '**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-emulator-

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: default
          emulator: true

      - name: Install System Image
        run: sdkmanager "system-images;android-31;default;x86_64"

      - name: Create Emulator (if not cached)
        run: |
          if [ ! -d ~/.android/avd/test.avd ]; then
            echo "Creating Emulator"
            echo "no" | avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --force
          fi

      - name: Start Emulator
        run: |
          nohup emulator -avd test -no-snapshot-save -no-audio -no-window &
          adb wait-for-device

      - name: Verify Emulator is Running
        run: adb shell getprop init.svc.bootanim | grep stopped

      - name: Run Compose UI Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: app/build/reports/androidTests/connected/
